"""baseline_canonical

Revision ID: c19572fedd66
Revises: 
Create Date: 2025-12-23 20:50:55.160991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c19572fedd66'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=False),
    sa.Column('event_data', sa.Text(), nullable=False),
    sa.Column('event_hash', sa.String(length=64), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=True),
    sa.Column('chain_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('LENGTH(chain_hash) = 64', name='ck_audit_chain_hash_len'),
    sa.CheckConstraint('LENGTH(event_hash) = 64', name='ck_audit_event_hash_len'),
    sa.CheckConstraint('prev_hash IS NULL OR LENGTH(prev_hash) = 64', name='ck_audit_prev_hash_len'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_actor'), 'audit_log', ['actor'], unique=False)
    op.create_index(op.f('ix_audit_log_chain_hash'), 'audit_log', ['chain_hash'], unique=True)
    op.create_index(op.f('ix_audit_log_entity_id'), 'audit_log', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_log_entity_type'), 'audit_log', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_log_event_hash'), 'audit_log', ['event_hash'], unique=False)
    op.create_table('configentry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_index(op.f('ix_configentry_id'), 'configentry', ['id'], unique=False)
    op.create_table('emission_factor',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('material_code', sa.String(length=100), nullable=False),
    sa.Column('material_name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('co2e_per_unit', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('factor_hash', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.CheckConstraint("factor_hash ~ '^[0-9a-f]{64}$'", name='ck_factor_hash_format'),
    sa.CheckConstraint('co2e_per_unit > 0', name='ck_positive_co2'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('factor_hash'),
    sa.UniqueConstraint('material_code', 'version', name='uq_material_code_version')
    )
    op.create_index('ix_emission_factor_active', 'emission_factor', ['material_code', 'is_active'], unique=False)
    op.create_table('lab',
    sa.Column('lab_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('accreditation', sa.String(length=100), nullable=True),
    sa.Column('contact', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('lab_id')
    )
    op.create_table('mrv_event_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ref_type', sa.String(length=50), nullable=False),
    sa.Column('ref_id', sa.String(length=50), nullable=False),
    sa.Column('event', sa.String(length=255), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_mrv_event_log_event', 'mrv_event_log', ['event'], unique=False)
    op.create_index('idx_mrv_event_log_ref', 'mrv_event_log', ['ref_type', 'ref_id'], unique=False)
    op.create_index('idx_mrv_event_log_ts', 'mrv_event_log', ['ts'], unique=False)
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Enum('ADMIN', 'PROJECT_MANAGER', 'CONTRACTOR', 'MRV_OFFICER', 'SUPPLIER', 'CITIZEN', name='role_name'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_role_id'), 'role', ['id'], unique=False)
    op.create_table('supplier',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('partnership_discount', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('total_value_supplied', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('project',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'IN_PROGRESS', 'COMPLETED', 'ARCHIVED', name='project_status'), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('budget_usd', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('anomaly_alert',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('token_uid', sa.String(length=36), nullable=True),
    sa.Column('rule_code', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='anomaly_severity'), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('numeric_value', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('threshold', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('(numeric_value IS NULL AND threshold IS NULL) OR (numeric_value IS NOT NULL AND threshold IS NOT NULL)', name='ck_anomaly_numeric_consistency'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anomaly_alert_rule_code'), 'anomaly_alert', ['rule_code'], unique=False)
    op.create_table('carbon_credit_issuance',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('credits_t', sa.Float(), nullable=False),
    sa.Column('value_usd', sa.Float(), nullable=False),
    sa.Column('credit_rate_usd_per_ton', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('calculation_details', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_carbon_credit_issuance_issued_at', 'carbon_credit_issuance', ['issued_at'], unique=False)
    op.create_index('idx_carbon_credit_issuance_project_id', 'carbon_credit_issuance', ['project_id'], unique=False)
    op.create_index('idx_carbon_credit_issuance_status', 'carbon_credit_issuance', ['status'], unique=False)
    op.create_table('carbon_credit_lifecycle',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('serial_number', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('issued', 'verified', 'approved', 'retired', name='carbon_credit_lifecycle_status'), nullable=False),
    sa.Column('co2e_amount_tonnes', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('methodology_version', sa.String(length=64), nullable=False),
    sa.Column('emission_factor_version', sa.String(length=64), nullable=False),
    sa.Column('issuer_id', sa.UUID(), nullable=False),
    sa.Column('verifier_id', sa.UUID(), nullable=False),
    sa.Column('approver_id', sa.UUID(), nullable=False),
    sa.Column('retired_by', sa.UUID(), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retirement_reason', sa.String(length=255), nullable=True),
    sa.Column('retirement_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("retired_at IS NULL OR (approved_at IS NOT NULL AND status = 'retired')", name='ck_ccl_retire_after_approval'),
    sa.CheckConstraint("status <> 'retired' OR (retired_at IS NOT NULL AND retired_by IS NOT NULL AND retirement_reason IS NOT NULL)", name='ck_ccl_retirement_requires_fields'),
    sa.CheckConstraint('approved_at IS NULL OR verified_at IS NOT NULL', name='ck_ccl_approve_after_verify'),
    sa.CheckConstraint('issuer_id IS DISTINCT FROM verifier_id AND verifier_id IS DISTINCT FROM approver_id AND issuer_id IS DISTINCT FROM approver_id', name='ck_ccl_separation_of_duties'),
    sa.CheckConstraint('verified_at IS NULL OR issued_at IS NOT NULL', name='ck_ccl_verify_after_issue'),
    sa.ForeignKeyConstraint(['approver_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['issuer_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['retired_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['verifier_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number'),
    sa.UniqueConstraint('serial_number', name='uq_ccl_serial')
    )
    op.create_index('ix_ccl_status_serial', 'carbon_credit_lifecycle', ['status', 'serial_number'], unique=False)
    op.create_table('material_token',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token_uid', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('material_code', sa.String(length=100), nullable=False),
    sa.Column('material_name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('supplier_name', sa.String(length=255), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('issued_by', sa.String(length=100), nullable=False),
    sa.Column('redeemed', sa.Boolean(), nullable=False),
    sa.Column('redeemed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_photo_path', sa.String(length=512), nullable=True),
    sa.Column('delivery_lat', sa.Float(), nullable=True),
    sa.Column('delivery_lon', sa.Float(), nullable=True),
    sa.Column('supplier_invoice_ref', sa.String(length=100), nullable=True),
    sa.CheckConstraint('quantity > 0', name='ck_material_token_positive_qty'),
    sa.CheckConstraint('redeemed = false OR (redeemed_at IS NOT NULL AND delivery_lat IS NOT NULL AND delivery_lon IS NOT NULL)', name='ck_material_token_redemption_complete'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'token_uid', name='uq_material_token_project_uid'),
    sa.UniqueConstraint('token_uid')
    )
    op.create_table('mrv_report',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('reporting_period', sa.String(length=50), nullable=False),
    sa.Column('emission_factor_id', sa.UUID(), nullable=True),
    sa.Column('sample_desc', sa.Text(), nullable=False),
    sa.Column('parameter', sa.String(length=255), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('total_co2e', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('certificate_path', sa.String(length=512), nullable=True),
    sa.Column('emission_factor_version_snapshot', sa.String(length=64), nullable=True),
    sa.Column('emission_factor_hash_snapshot', sa.String(length=64), nullable=True),
    sa.Column('emission_factor_value_snapshot', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'VERIFIED', 'APPROVED', 'LOCKED', name='mrv_status_workflow'), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('verified_by', sa.String(length=100), nullable=True),
    sa.Column('approved_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('emission_factor_hash_snapshot IS NULL OR char_length(emission_factor_hash_snapshot) = 64', name='ck_mrv_snapshot_hash_len'),
    sa.ForeignKeyConstraint(['emission_factor_id'], ['emission_factor.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mrv_sample',
    sa.Column('sample_id', sa.String(length=50), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('collected_by', sa.String(length=255), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('geotag_lat', sa.Numeric(precision=10, scale=8), nullable=False),
    sa.Column('geotag_lon', sa.Numeric(precision=11, scale=8), nullable=False),
    sa.Column('sample_type', sa.String(length=100), nullable=False),
    sa.Column('chain_of_custody', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('COLLECTED', 'SUBMITTED', 'IN_LAB', 'TESTED', 'APPROVED', 'REJECTED', name='mrv_sample_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mrv_flags', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('sample_id')
    )
    op.create_index('idx_mrv_sample_collected_at', 'mrv_sample', ['collected_at'], unique=False)
    op.create_index('idx_mrv_sample_project_id', 'mrv_sample', ['project_id'], unique=False)
    op.create_index('idx_mrv_sample_status', 'mrv_sample', ['status'], unique=False)
    op.create_table('public_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('total_co2_saved_t', sa.Numeric(precision=18, scale=6), nullable=False, comment='Total CO₂ emissions saved (metric tons)'),
    sa.Column('verified_co2_t', sa.Numeric(precision=18, scale=6), nullable=False, comment='Verified CO₂ (approved MRV reports only)'),
    sa.Column('total_materials_t', sa.Numeric(precision=18, scale=6), nullable=False, comment='Total materials delivered (metric tons)'),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_table('sensorreading',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('sensor_type', sa.Enum('ENERGY', 'WATER_SAVING', 'OTHER', name='sensor_type'), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=64), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('whistleblower',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('evidence_path', sa.String(length=512), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'OPEN', 'CLOSED', 'DISMISSED', name='whistleblower_status'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='whistleblower_priority'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chain_step',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sample_id', sa.String(length=50), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('evidence_file', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['sample_id'], ['mrv_sample.sample_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chain_step_sample_id', 'chain_step', ['sample_id'], unique=False)
    op.create_index('idx_chain_step_timestamp', 'chain_step', ['timestamp'], unique=False)
    op.create_table('delivery_verification',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('material_token_id', sa.UUID(), nullable=False),
    sa.Column('photo_path', sa.String(length=512), nullable=False),
    sa.Column('photo_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('delivery_lat', sa.Float(), nullable=False),
    sa.Column('delivery_lon', sa.Float(), nullable=False),
    sa.Column('gps_hash', sa.String(length=64), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified_by', sa.String(length=100), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verification_notes', sa.Text(), nullable=True),
    sa.CheckConstraint('LENGTH(gps_hash) = 64', name='ck_delivery_verification_gps_hash_format'),
    sa.CheckConstraint('LENGTH(photo_fingerprint) = 64', name='ck_delivery_verification_photo_hash_format'),
    sa.CheckConstraint('delivery_lat >= -90 AND delivery_lat <= 90', name='ck_delivery_verification_valid_lat'),
    sa.CheckConstraint('delivery_lon >= -180 AND delivery_lon <= 180', name='ck_delivery_verification_valid_lon'),
    sa.ForeignKeyConstraint(['material_token_id'], ['material_token.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('material_token_id')
    )
    op.create_index(op.f('ix_delivery_verification_gps_hash'), 'delivery_verification', ['gps_hash'], unique=False)
    op.create_index(op.f('ix_delivery_verification_photo_fingerprint'), 'delivery_verification', ['photo_fingerprint'], unique=False)
    op.create_table('mrv_test',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sample_id', sa.String(length=50), nullable=False),
    sa.Column('lab_id', sa.String(length=36), nullable=False),
    sa.Column('parameter', sa.String(length=255), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('method', sa.String(length=255), nullable=False),
    sa.Column('certificate_file', sa.String(length=512), nullable=True),
    sa.Column('certificate_hash', sa.String(length=64), nullable=True),
    sa.Column('lab_report_id', sa.String(length=100), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('co2_contribution_kg', sa.Float(), nullable=True),
    sa.Column('lca_method', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lab_id'], ['lab.lab_id'], ),
    sa.ForeignKeyConstraint(['sample_id'], ['mrv_sample.sample_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_mrv_test_lab_id', 'mrv_test', ['lab_id'], unique=False)
    op.create_index('idx_mrv_test_parameter', 'mrv_test', ['parameter'], unique=False)
    op.create_index('idx_mrv_test_sample_id', 'mrv_test', ['sample_id'], unique=False)
    op.create_table('carbon_ledger',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('sample_id', sa.String(length=50), nullable=False),
    sa.Column('test_id', sa.String(length=36), nullable=True),
    sa.Column('co2_kg', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('material_type', sa.String(length=100), nullable=False),
    sa.Column('quantity_tonnes', sa.Float(), nullable=True),
    sa.Column('lca_method', sa.String(length=100), nullable=True),
    sa.Column('calculation_details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['sample_id'], ['mrv_sample.sample_id'], ),
    sa.ForeignKeyConstraint(['test_id'], ['mrv_test.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_carbon_ledger_created_at', 'carbon_ledger', ['created_at'], unique=False)
    op.create_index('idx_carbon_ledger_project_id', 'carbon_ledger', ['project_id'], unique=False)
    op.create_index('idx_carbon_ledger_sample_id', 'carbon_ledger', ['sample_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_carbon_ledger_sample_id', table_name='carbon_ledger')
    op.drop_index('idx_carbon_ledger_project_id', table_name='carbon_ledger')
    op.drop_index('idx_carbon_ledger_created_at', table_name='carbon_ledger')
    op.drop_table('carbon_ledger')
    op.drop_index('idx_mrv_test_sample_id', table_name='mrv_test')
    op.drop_index('idx_mrv_test_parameter', table_name='mrv_test')
    op.drop_index('idx_mrv_test_lab_id', table_name='mrv_test')
    op.drop_table('mrv_test')
    op.drop_index(op.f('ix_delivery_verification_photo_fingerprint'), table_name='delivery_verification')
    op.drop_index(op.f('ix_delivery_verification_gps_hash'), table_name='delivery_verification')
    op.drop_table('delivery_verification')
    op.drop_index('idx_chain_step_timestamp', table_name='chain_step')
    op.drop_index('idx_chain_step_sample_id', table_name='chain_step')
    op.drop_table('chain_step')
    op.drop_table('whistleblower')
    op.drop_table('sensorreading')
    op.drop_table('public_metrics')
    op.drop_index('idx_mrv_sample_status', table_name='mrv_sample')
    op.drop_index('idx_mrv_sample_project_id', table_name='mrv_sample')
    op.drop_index('idx_mrv_sample_collected_at', table_name='mrv_sample')
    op.drop_table('mrv_sample')
    op.drop_table('mrv_report')
    op.drop_table('material_token')
    op.drop_index('ix_ccl_status_serial', table_name='carbon_credit_lifecycle')
    op.drop_table('carbon_credit_lifecycle')
    op.drop_index('idx_carbon_credit_issuance_status', table_name='carbon_credit_issuance')
    op.drop_index('idx_carbon_credit_issuance_project_id', table_name='carbon_credit_issuance')
    op.drop_index('idx_carbon_credit_issuance_issued_at', table_name='carbon_credit_issuance')
    op.drop_table('carbon_credit_issuance')
    op.drop_index(op.f('ix_anomaly_alert_rule_code'), table_name='anomaly_alert')
    op.drop_table('anomaly_alert')
    op.drop_table('project')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('supplier')
    op.drop_index(op.f('ix_role_id'), table_name='role')
    op.drop_table('role')
    op.drop_index('idx_mrv_event_log_ts', table_name='mrv_event_log')
    op.drop_index('idx_mrv_event_log_ref', table_name='mrv_event_log')
    op.drop_index('idx_mrv_event_log_event', table_name='mrv_event_log')
    op.drop_table('mrv_event_log')
    op.drop_table('lab')
    op.drop_index('ix_emission_factor_active', table_name='emission_factor')
    op.drop_table('emission_factor')
    op.drop_index(op.f('ix_configentry_id'), table_name='configentry')
    op.drop_table('configentry')
    op.drop_index(op.f('ix_audit_log_event_hash'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entity_type'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entity_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_chain_hash'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_actor'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
